public enum GameType
{
    VOCABULARY,
}

public enum GameTypeInternal
{
    VOCABULARY_DRAW_LETTER,
    VOCABULARY_FIND_LETTER,
    VOCABULARY_FIND_ALL_LETTERS,
    VOCABULARY_FIND_WORD_BASED_ON_LETTER
}