public enum GameType
{
    VOCABULARY,
}

public enum GameTypeInternal
{
    VOCABULARY_DRAW_LETTER,
    VOCABULARY_FIND_LETTER,
    VOCABULARY_FIND_ALLLETERS,
    VOCABULARY_FIND_WORD_BASEDONLETTER
}